# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-17 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=120)),
                ('fullname', models.CharField(max_length=120)),
                ('purchase', models.DecimalField(decimal_places=2, max_digits=7)),
                ('contacted', models.BooleanField()),
                ('city', models.CharField(max_length=120)),
                ('country', models.CharField(choices=[('UYU', 'Uruguay'), ('ARG', 'Argentina'), ('BRA', 'Brazil'), ('PRY', 'Parguay')], max_length=3)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
