# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aduana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guia_de_transito', models.DecimalField(decimal_places=2, default=6, max_digits=8)),
                ('timbre_profesional', models.DecimalField(decimal_places=2, default=6, max_digits=8)),
                ('recargo', models.DecimalField(decimal_places=4, default=0.02, max_digits=8)),
                ('iva', models.DecimalField(decimal_places=4, default=0.22, max_digits=8)),
                ('anticipo_iva', models.DecimalField(decimal_places=4, default=0.1, max_digits=8)),
                ('cert_empadronamiento', models.DecimalField(decimal_places=2, default=15, max_digits=7)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Extraordinario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cif_low', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cif_up', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=800, max_digits=8)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('despachante', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, default=90, max_digits=8)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Honorarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('despachante', models.CharField(max_length=120)),
                ('cif_low', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cif_up', models.DecimalField(decimal_places=2, max_digits=8)),
                ('percentage', models.DecimalField(decimal_places=4, max_digits=8)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=1500, max_digits=8)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Puerto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratio_low', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ratio_up', models.DecimalField(decimal_places=2, max_digits=8)),
                ('multiplicator', models.DecimalField(decimal_places=2, max_digits=6)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tsa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cif_low', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cif_up', models.DecimalField(decimal_places=2, max_digits=8)),
                ('percentage', models.DecimalField(decimal_places=4, default=0.2, max_digits=8)),
                ('fix', models.DecimalField(decimal_places=2, default=50, max_digits=8)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomBrokerPrice',
        ),
        migrations.DeleteModel(
            name='CustomUruguay',
        ),
        migrations.DeleteModel(
            name='ExtraordinarioPrice',
        ),
        migrations.DeleteModel(
            name='PortPrice',
        ),
        migrations.DeleteModel(
            name='TasaServicioAduana',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='name',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='purchase_price',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='sale_price',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='sold_price',
        ),
        migrations.AddField(
            model_name='machine',
            name='brand',
            field=models.CharField(default='Case', max_length=120),
        ),
        migrations.AddField(
            model_name='machine',
            name='height',
            field=models.DecimalField(decimal_places=2, default=3.8, max_digits=8),
        ),
        migrations.AddField(
            model_name='machine',
            name='kind',
            field=models.CharField(default='retroexcavadora', max_length=120),
        ),
        migrations.AddField(
            model_name='machine',
            name='model',
            field=models.CharField(default='580 SLE', max_length=120),
        ),
        migrations.AddField(
            model_name='taxcountry',
            name='currency',
            field=models.CharField(default='EUR', max_length=3),
        ),
        migrations.AddField(
            model_name='transport',
            name='currency',
            field=models.CharField(default='EUR', max_length=3),
        ),
        migrations.AddField(
            model_name='transport',
            name='name',
            field=models.CharField(default='Soccar Shipping Agency', max_length=120),
        ),
        migrations.AlterField(
            model_name='machine',
            name='length',
            field=models.DecimalField(decimal_places=2, default=5.56, max_digits=8),
        ),
        migrations.AlterField(
            model_name='machine',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=8, max_digits=8),
        ),
        migrations.AlterField(
            model_name='machine',
            name='width',
            field=models.DecimalField(decimal_places=2, default=5.56, max_digits=8),
        ),
        migrations.AlterField(
            model_name='taxcountry',
            name='country',
            field=models.CharField(default='Denmark', max_length=120),
        ),
        migrations.AlterField(
            model_name='taxcountry',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=375, max_digits=8),
        ),
        migrations.AlterField(
            model_name='transport',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=440, max_digits=8),
        ),
    ]
