# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_auto_20160704_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='comment',
            field=models.CharField(default='No bucket', max_length=120),
        ),
        migrations.AlterField(
            model_name='extraordinario',
            name='cif_low',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='extraordinario',
            name='cif_up',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='extraordinario',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='honorarios',
            name='cif_low',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='honorarios',
            name='cif_up',
            field=models.DecimalField(decimal_places=2, default=25000, max_digits=8),
        ),
        migrations.AlterField(
            model_name='honorarios',
            name='despachante',
            field=models.CharField(default='Navatta', max_length=120),
        ),
        migrations.AlterField(
            model_name='honorarios',
            name='percentage',
            field=models.DecimalField(decimal_places=4, default=1.5, max_digits=8),
        ),
        migrations.AlterField(
            model_name='tsa',
            name='cif_low',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='tsa',
            name='cif_up',
            field=models.DecimalField(decimal_places=2, default=25000.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='tsa',
            name='fix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
