# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_auto_20160705_0439'),
    ]

    operations = [
        migrations.AddField(
            model_name='aduana',
            name='city',
            field=models.CharField(default='Denmark', max_length=120),
        ),
    ]
