# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0006_auto_20160705_0445'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraordinario',
            name='name',
            field=models.CharField(default='Escala 1', max_length=120),
        ),
        migrations.AddField(
            model_name='flete',
            name='name',
            field=models.CharField(default='Full Cargo', max_length=120),
        ),
        migrations.AddField(
            model_name='kma',
            name='name',
            field=models.CharField(default='KMA', max_length=120),
        ),
        migrations.AddField(
            model_name='puerto',
            name='name',
            field=models.CharField(default='Escala 1', max_length=120),
        ),
        migrations.AddField(
            model_name='tsa',
            name='name',
            field=models.CharField(default='Escala 1', max_length=120),
        ),
        migrations.AlterField(
            model_name='gastos',
            name='despachante',
            field=models.CharField(default='Navatta', max_length=120),
        ),
    ]
