# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0007_auto_20160705_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aduana',
            name='anticipo_iva',
            field=models.DecimalField(decimal_places=4, default=0.1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='aduana',
            name='guia_de_transito',
            field=models.DecimalField(decimal_places=2, default=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='aduana',
            name='iva',
            field=models.DecimalField(decimal_places=4, default=0.22, max_digits=10),
        ),
        migrations.AlterField(
            model_name='aduana',
            name='recargo',
            field=models.DecimalField(decimal_places=4, default=0.02, max_digits=10),
        ),
        migrations.AlterField(
            model_name='aduana',
            name='timbre_profesional',
            field=models.DecimalField(decimal_places=2, default=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='extraordinario',
            name='cif_low',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='extraordinario',
            name='cif_up',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='extraordinario',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='flete',
            name='price',
            field=models.DecimalField(decimal_places=2, default=800, max_digits=10),
        ),
        migrations.AlterField(
            model_name='gastos',
            name='price',
            field=models.DecimalField(decimal_places=2, default=90, max_digits=10),
        ),
        migrations.AlterField(
            model_name='honorarios',
            name='cif_low',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='honorarios',
            name='cif_up',
            field=models.DecimalField(decimal_places=2, default=25000, max_digits=10),
        ),
        migrations.AlterField(
            model_name='honorarios',
            name='percentage',
            field=models.DecimalField(decimal_places=4, default=1.5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='kma',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1500, max_digits=10),
        ),
        migrations.AlterField(
            model_name='machine',
            name='height',
            field=models.DecimalField(decimal_places=2, default=3.8, max_digits=10),
        ),
        migrations.AlterField(
            model_name='machine',
            name='length',
            field=models.DecimalField(decimal_places=2, default=5.56, max_digits=10),
        ),
        migrations.AlterField(
            model_name='machine',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=8, max_digits=10),
        ),
        migrations.AlterField(
            model_name='machine',
            name='width',
            field=models.DecimalField(decimal_places=2, default=5.56, max_digits=10),
        ),
        migrations.AlterField(
            model_name='puerto',
            name='ratio_low',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='puerto',
            name='ratio_up',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='taxcountry',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=375, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transport',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=440, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tsa',
            name='cif_low',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tsa',
            name='cif_up',
            field=models.DecimalField(decimal_places=2, default=25000.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tsa',
            name='fix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tsa',
            name='percentage',
            field=models.DecimalField(decimal_places=4, default=0.2, max_digits=10),
        ),
    ]
