# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0009_auto_20160705_0506'),
    ]

    operations = [
        migrations.AddField(
            model_name='honorarios',
            name='name',
            field=models.CharField(default='Escala 1', max_length=120),
        ),
    ]
