# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0013_inspection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank_Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Itau', max_length=120)),
                ('transfer_out_local', models.DecimalField(decimal_places=2, default=10, max_digits=10)),
                ('transfer_in_local', models.DecimalField(decimal_places=2, default=10, max_digits=10)),
                ('transfer_out_international', models.DecimalField(decimal_places=2, default=150, max_digits=10)),
                ('commission_usd_eur', models.DecimalField(decimal_places=2, default=10, max_digits=10)),
                ('various', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=120)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cost_Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Agency R.', max_length=120)),
                ('plane', models.DecimalField(decimal_places=2, default=500, max_digits=10)),
                ('train', models.DecimalField(decimal_places=2, default=150, max_digits=10)),
                ('car', models.DecimalField(decimal_places=2, default=30, max_digits=10)),
                ('phone', models.DecimalField(decimal_places=2, default=10, max_digits=10)),
                ('various', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cost_Sell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Mercyl', max_length=120)),
                ('car', models.DecimalField(decimal_places=2, default=150, max_digits=10)),
                ('phone', models.DecimalField(decimal_places=2, default=30, max_digits=10)),
                ('mercado_libre', models.DecimalField(decimal_places=2, default=50, max_digits=10)),
                ('work', models.DecimalField(decimal_places=2, default=200, max_digits=10)),
                ('various', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fix_Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contadora', models.DecimalField(decimal_places=2, default=170, max_digits=10)),
                ('irae', models.DecimalField(decimal_places=2, default=2000, max_digits=10)),
                ('icosa', models.DecimalField(decimal_places=2, default=600, max_digits=10)),
                ('bss', models.DecimalField(decimal_places=2, default=70, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('dividend', models.DecimalField(decimal_places=2, default=0.05, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='machine',
            name='comment',
            field=models.CharField(default='', max_length=120),
        ),
    ]
