# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0014_auto_20160719_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost_sell',
            name='nafta_maquina',
            field=models.DecimalField(decimal_places=2, default=80, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fix_cost',
            name='currency',
            field=models.CharField(default='UYU', max_length=3),
        ),
    ]
