# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0015_auto_20160719_0743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taxes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='taxes', max_length=3)),
                ('irae', models.DecimalField(decimal_places=2, default=0.25, max_digits=10)),
                ('icosa', models.DecimalField(decimal_places=2, default=12852, max_digits=10)),
                ('bss', models.DecimalField(decimal_places=2, default=70, max_digits=10)),
                ('dividend', models.DecimalField(decimal_places=2, default=0.05, max_digits=10)),
                ('currency', models.CharField(default='UYU', max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='fix_cost',
            name='bss',
        ),
        migrations.RemoveField(
            model_name='fix_cost',
            name='contadora',
        ),
        migrations.RemoveField(
            model_name='fix_cost',
            name='dividend',
        ),
        migrations.RemoveField(
            model_name='fix_cost',
            name='icosa',
        ),
        migrations.RemoveField(
            model_name='fix_cost',
            name='irae',
        ),
        migrations.AddField(
            model_name='fix_cost',
            name='annual',
            field=models.DecimalField(decimal_places=2, default=5124, max_digits=10),
        ),
        migrations.AddField(
            model_name='fix_cost',
            name='name',
            field=models.CharField(default='contadora', max_length=3),
        ),
    ]
