# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 14:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0016_auto_20160719_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank_cost',
            name='various',
        ),
    ]
