# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0018_auto_20160719_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxes',
            name='name',
            field=models.CharField(default='taxes', max_length=120),
        ),
    ]
