# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0019_auto_20160719_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport_Anvers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='generic', max_length=120)),
                ('annual', models.DecimalField(decimal_places=2, default=500, max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
